language: node_js
sudo: false
node_js:
- '6.0.0'
- '8.1.2'
- 'stable'
install:
- .travis/maybe-install.sh
before_script:
- .travis/maybe-check-scope.sh
script:
- .travis/maybe-test.sh
- .travis/maybe-check-coverage.sh
- .travis/maybe-bump-version.sh
after_success:
- .travis/maybe-publish-coverage.sh
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: uAlbMZYFTiu7iLa4Yr99L6bmVxOpvDwGI9fVduNvbhZresu26VXOrI6YxtFgSIOjtgd5GZi8k0CXxJ28dUDQewMtBVEZ+Z8kYLSYITRXjWaIitL+N+D8EjVCWHEYDAgQm2C2GlowICgu2PxqNczgsS7fYzOwMncOWLJ3ybIJcFqnGaCG7BYXsLCfMDSPNFQuHxdkzDfOhJjqpuzTUxLiwcWkZsHQ2m1Z1ueRM9+umTWw7py9M3BqbjqHvDnJLdgEsWHwZBKEaMdOYKWTxK/E1JazIpjB98iuhrofG4VDNB4e0sOMo9O9wo2JXFsLZV3v5Ka5hkPp/sV25zgMyn3VToniJPEZuZlYycCQZCzeMyzJVbLEpWBDTz2x0cWsimF8XV+No2BoSllxQp2bhG4xD9O+l963J0bPNZy/2DRnu53vcpJORliFt+dpQJMe1q0ytsLlvaW4NZXJpXHfVvC+4ubnS5JPALbXYs4oO32qmP1uhY87aepeq3zzdvqYIQJLdmC67vw/dUNHTMat+7K3cEznzJjoTU7Pe+UFOM/5oyJPQV+lHq3HSD4CUx0rEmOHTv86dXeppLGsdrTErwmbxYHXiBNKdhufRf1bVMBxTV7yuif7pll1Sh2duw7vetjO2eT0b47T85JvpUllts1sID+PXNsxkp0dM5GlioL29oY=

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'stable'

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: iuTuGxrHPIoUjUMrWi+qcG9zVqMh/7dCk51Kbcl2lpJF9fkNQyqFGJhCUnPzJ91H67s7EfjyrscWoOpdaxX/9PQ5rrufmdM/rQxryxDIY4ZuOxXiGmZVFAygJflbgPvK37KOaUOT84Y8V0fcV/wqJcd2JIjLKmU2gX6nflLRcqCohh6cUGXyaXitEGCa9K5PBixtzMa6nIAf1+c+oGT9emc1ZTwcch5eOBBbur/fG7eeNE2OMqCDvCwy18ABb6MonZhLZypXBxrOGNqpx5AASxaovjJrMq+gC6W0fqFqdISYNzJh1pDGnpetcy4jV1DzwOJIEl58osO1Uu2GgsSj4IqHTLWuahB2B+iKdfaHA4XtcioXj1fAVKiNPE0bWeLz/sezfrU2uwoMpYQjUCd/Cd4Dc6tQPlhIRqK59TpZ04Yf+zJbgY1switWhmcD5XKxpfRfbY2VdNG6HKB9EECP7sxu4DhroDY+xMGyVMf2RXB9GkbNLeBWzJ2Q2NDWh05XCZm/N50NYY/ntG/PBUVQsDZYerZVFCCALRcyOIVwsIHxiLtZhO+r88Pog7A48CFY2DmMxfXKUFezJPlA1yqXNJDztYVGFUgI1hzY26UbrcmM+mA9ZlRxoxzTuvFYYpgpLrjjOmkUszzlbEsfTbu1t1SYFkiMxIoMXZ80iLAtQgg=
  on:
    all_branches: true
    node: '8.1.2'
    tags: true
notifications:
  slack:
    secure: HhIw/Pe6j7jiGwC5pwv8MQKt4a+WBhcpffEWsW7+JTn0sJfXzArltZXO6bwAgHtF7x/ZCyqJFruUdaxHI2MQ4khwZC2HrnYl2Fnpse7wQOgkEOyuzGYpowDnn6iak18+R8CYV9r57Ah27nzJbx936D65hYetCIVX8ZHvHmdKUOvNyXbXsaBGdj828JUllnxXZy8IZpFvzrbZlnMCOdr9mkt7nkTr6TErTMbHVbk5v4voGBw3/JyzaksLCWfTvNta82GI3kwPvGlnFHRBAUtOGW4l29HIWilJlqnq3KyjX2d02DfpK+kVllpwwwO+fRkF0Wd0K/p1OgR/VKajOZFeranvSEPlZMA4IoRZGrjaFCJ3Z5V4/Dmkm6KqotuYWzS16f7NHAhAJOE7sFDetlymT019spDKtf0gQRUdb0F+AEZ1CpikUb2ybZw6xNbB3oDQkBsmoU2+uItj93Z8yV3XZVkjSjF9mhZ1UYC0f45+GfxRedD7AdfceQObrF3LbssMxTZLMzeuPMfIq1rzlR5m3+Sdd0yuie/Ni13gWackYTg+cn+5ESDGat5oR2s/Lg3lnCNBMqRl5x//nY5PYIrXzg8VvOXRrE92eAiVQJ4urAKS92KhIBBeh3JrTzf03gRSIE9be+G864TZ3ofWUvvpuRXNON31QWUFtyO8K9z3g+8=
